base:
  project: ai4i2020-project
  random_state: 999
  target_col: "Air temperature [K]"

data_source:
  s3_source: data_given/ai4i2020.csv
  

load_data:
  raw_dataset_csv: data/raw/ai4i2020.csv

split_data:
  train_path: data/processed/train_ai4i2020.csv
  test_path: data/processed/test_ai4i2020.csv
  test_size: 0.35

model_dir: saved_models

reports:
  scores: report/scores.json
  roc: report/roc.json
  prc: report/prc.json
  auc: report/auc.json

